name: Build C/C++

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linux:
    name: Linux Build
    runs-on: ubuntu-latest
    container: ubuntu:18.04

    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
      ACTIONS_RUNNER_FORCED_INTERNAL_NODE_VERSION: node16
      ACTIONS_RUNNER_FORCE_ACTIONS_NODE_VERSION: node16

    steps:
    - name: Setup Checkout
      uses: actions/checkout@v3
      
    - name: Add i386 architecture
      run: dpkg --add-architecture i386
      
    - name: Update repository
      run: apt-get update

    - name: Install build dependencies
      run: apt-get install -qq -y wget unzip build-essential gcc-4.8-multilib g++-4.8-multilib libgcc1:i386
    
    - name: Update alternatives
      run: update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 100 --slave /usr/bin/g++ g++ /usr/bin/g++-4.8
   
    - name: Run build
      working-directory: ./AccuracyFix
      run: make
    
    - name: Make Accuracy Fix path
      run: mkdir -p publish/addons/accuracyfix/dlls

    - name: Make Accuracy Fix path
      run: mv ./AccuracyFix/Release/accuracyfix_mm.so publish/addons/accuracyfix/dlls
      
    - name: Move settings file to folder
      run: mv ./cstrike/addons/accuracyfix/accuracyfix.cfg publish/addons/accuracyfix/accuracyfix.cfg

    - name: Deploy artifacts
      uses: actions/upload-artifact@v3
      with:
        name: linux32
        path: publish/*
        
  windows:
    name: Windows Build
    runs-on: windows-latest
      
    env:
      SOLUTION_FILE_PATH: .
      BUILD_CONFIGURATION: Release
  
    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Run Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}

    - name: Move release file to publish
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        # Make publish directory
        mkdir publish\addons\accuracyfix\dlls

        # Move released dll to publish
        move ${{env.BUILD_CONFIGURATION}}\*.dll publish\addons\accuracyfix\dlls

        # Move settings file to folder
        mv ${{env.SOLUTION_FILE_PATH}}\cstrike\addons\accuracyfix\accuracyfix.cfg publish\addons\accuracyfix\accuracyfix.cfg

    - name: Deploy artifacts
      uses: actions/upload-artifact@v4
      with:
        name: win32
        path: publish/*
        
        
        
